'use strict';
/*
 * The motion backgrounds offered in the Presentation Studio.
 *
 * GENERATED by scripts/build-bg-videos.js — edit the curated list there, not here.
 *
 * Only the poster ships with the app (assets/bgvideos/<id>.jpg, a few kB each).
 * The clip itself is fetched once, on the click that chooses it, and lands in
 * <userData>/backgrounds — after which it plays with the network unplugged,
 * which is the only state that matters on a Sunday morning.
 *
 * Footage: Pixabay (pixabay.com), Pixabay Content License.
 */
(() => {
  const CLIPS = [
  { id: '70216', name: "Open Bible", cat: 'Faith', url: 'https://cdn.pixabay.com/video/2021/04/06/70216-533814725_small.mp4', bytes: 12033265, w: 1920, h: 1080, secs: 24 },
  { id: '150149', name: "Scripture & Light", cat: 'Faith', url: 'https://cdn.pixabay.com/video/2023/02/11/150149-797999298_large.mp4', bytes: 20792227, w: 1920, h: 1080, secs: 80 },
  { id: '117183', name: "Bible & Candles", cat: 'Faith', url: 'https://cdn.pixabay.com/video/2022/05/16/117183-710602933_large.mp4', bytes: 12180725, w: 1920, h: 1080, secs: 61 },
  { id: '139047', name: "Oil Lamp", cat: 'Faith', url: 'https://cdn.pixabay.com/video/2022/11/15/139047-771365739_large.mp4', bytes: 4940853, w: 1920, h: 1080, secs: 80 },
  { id: '139046', name: "Candlelit Book", cat: 'Faith', url: 'https://cdn.pixabay.com/video/2022/11/15/139046-771365734_large.mp4', bytes: 4359472, w: 1920, h: 1080, secs: 80 },
  { id: '134964', name: "Scripture & Bokeh", cat: 'Faith', url: 'https://cdn.pixabay.com/video/2022/10/15/134964-760679909_large.mp4', bytes: 13883141, w: 1920, h: 1080, secs: 60 },
  { id: '106885', name: "Quiet Study", cat: 'Faith', url: 'https://cdn.pixabay.com/video/2022/02/06/106885-674268702_large.mp4', bytes: 16762180, w: 1920, h: 1080, secs: 60 },
  { id: '214405', name: "Rose Light", cat: 'Light', url: 'https://cdn.pixabay.com/video/2024/05/29/214405_large.mp4', bytes: 30530326, w: 1920, h: 1080, secs: 30 },
  { id: '219969', name: "Blue Rays", cat: 'Light', url: 'https://cdn.pixabay.com/video/2024/07/07/219969_large.mp4', bytes: 25109592, w: 1920, h: 1080, secs: 8 },
  { id: '217486', name: "Starlight", cat: 'Light', url: 'https://cdn.pixabay.com/video/2024/06/20/217486_large.mp4', bytes: 40949589, w: 1920, h: 1080, secs: 8 },
  { id: '214402', name: "Purple Haze", cat: 'Light', url: 'https://cdn.pixabay.com/video/2024/05/29/214402_large.mp4', bytes: 15905234, w: 1920, h: 1080, secs: 8 },
  { id: '183558', name: "Candle Flames", cat: 'Light', url: 'https://cdn.pixabay.com/video/2023/10/05/183558-871642742_small.mp4', bytes: 35908760, w: 1920, h: 1080, secs: 80 },
  { id: '165208', name: "Soft Bokeh", cat: 'Light', url: 'https://cdn.pixabay.com/video/2023/05/31/165208-832102298_small.mp4', bytes: 10282213, w: 1920, h: 1080, secs: 29 },
  { id: '175953', name: "Forest River", cat: 'Nature', url: 'https://cdn.pixabay.com/video/2023/08/14/175953-854496176_small.mp4', bytes: 43168873, w: 1920, h: 1080, secs: 60 },
  { id: '169880', name: "Misty Path", cat: 'Nature', url: 'https://cdn.pixabay.com/video/2023/07/03/169880-841954078_small.mp4', bytes: 30748071, w: 1920, h: 1080, secs: 60 },
  { id: '174588', name: "Hidden Falls", cat: 'Nature', url: 'https://cdn.pixabay.com/video/2023/08/04/174588-851804340_small.mp4', bytes: 17244569, w: 1920, h: 1080, secs: 60 },
  { id: '201447', name: "Meadow", cat: 'Nature', url: 'https://cdn.pixabay.com/video/2024/02/21/201447-915698694_large.mp4', bytes: 18483606, w: 1920, h: 1080, secs: 26 },
  { id: '236711', name: "Campfire", cat: 'Nature', url: 'https://cdn.pixabay.com/video/2024/10/17/236711_small.mp4', bytes: 15109452, w: 1920, h: 1080, secs: 8 },
  { id: '178807', name: "Sea Sunset", cat: 'Water', url: 'https://cdn.pixabay.com/video/2023/09/02/178807-860734626_large.mp4', bytes: 31734677, w: 1920, h: 1080, secs: 45 },
  { id: '178809', name: "Evening Shore", cat: 'Water', url: 'https://cdn.pixabay.com/video/2023/09/02/178809-860734631_large.mp4', bytes: 22005265, w: 1920, h: 1080, secs: 30 },
  { id: '174468', name: "Sunset Sphere", cat: 'Water', url: 'https://cdn.pixabay.com/video/2023/08/03/174468-851502076_small.mp4', bytes: 21692617, w: 1920, h: 1080, secs: 60 },
  { id: '173656', name: "Tree of Light", cat: 'Water', url: 'https://cdn.pixabay.com/video/2023/07/29/173656-849839042_small.mp4', bytes: 25262010, w: 1920, h: 1080, secs: 60 },
  { id: '165229', name: "Golden Dust", cat: 'Abstract', url: 'https://cdn.pixabay.com/video/2023/05/31/165229-832460001_small.mp4', bytes: 7603403, w: 1920, h: 1080, secs: 10 },
  { id: '178799', name: "Blue Lines", cat: 'Abstract', url: 'https://cdn.pixabay.com/video/2023/09/02/178799-860734620_large.mp4', bytes: 10716951, w: 1920, h: 1080, secs: 14 },
  { id: '203021', name: "Ribbons", cat: 'Abstract', url: 'https://cdn.pixabay.com/video/2024/03/04/203021-919745637_large.mp4', bytes: 6042635, w: 1920, h: 1080, secs: 10 },
  { id: '202583', name: "Warm Spiral", cat: 'Abstract', url: 'https://cdn.pixabay.com/video/2024/03/01/202583-918431492_large.mp4', bytes: 7759239, w: 1920, h: 1080, secs: 10 },
  { id: '93079', name: "Harvest Bible", cat: 'Season', url: 'https://cdn.pixabay.com/video/2021/10/24/93079-639008190_small.mp4', bytes: 14338018, w: 1920, h: 1080, secs: 60 },
  { id: '143328', name: "Winter Candle", cat: 'Season', url: 'https://cdn.pixabay.com/video/2022/12/17/143328-782178570_large.mp4', bytes: 40950062, w: 1920, h: 1080, secs: 60 },
  ];
  const CATEGORIES = ["Faith","Light","Nature","Water","Abstract","Season"];
  const byId = (id) => CLIPS.find((c) => c.id === String(id)) || null;
  window.BgVideos = { CLIPS, CATEGORIES, byId };
})();
